version: '3'
services:
  postgres:
    image: postgres:14
    container_name: typeorm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: typeorm_demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: